### ISSUE TITLE
enable e2e tests in CI pipelines

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2309]
To ensure, that our application is always building and runnable, we need to write and enable end to end tests for our business processes.

To ensure, that this tests are always green, we need to run them on each PR as part of our CI testing routine.

**Comment by sleidig** [comment]
on hold until e2e tests are implemented:
- #2612

**Comment by sleidig** [comment]
a possible Github Action for the CI job:
```
name: Playwright Tests
on:
  push:
    branches: [ main, master, e2e_Tests ]
  pull_request:
    branches: [ main, master, e2e_Tests ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

(this doesn't run properly yet, however ...)
